// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // assegura que o valor é tratado como string (evita erro de tipo quando undefined)
    url: process.env["DATABASE_URL"] as string,
  },
});
